apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-deployment
 labels:
  app: flaskapp

spec:
 replicas: 3
 selector:
  matchLabels:
   app: flaskapp
    
 template:
  metadata:
   labels:
    app: flaskapp

  spec:
   containers:
    - name: flaskapp
      image: babaknasrolahy/flaskapp:latest
      ports:
      - containerPort: 80

   imagePullSecrets:
    - name: registrypullsecret

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service

spec:
  type: LoadBalancer
  selector:
    app: flaskapp
  
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30000

