apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlltRmlZV3R1WVhOeWIyeGhhSGs2UWtBeE16Z3pMa0poWW1GciIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: flask-deployment
 labels:
  app: flaskapp

spec:
 replicas: 1
 selector:
  matchLabels:
   app: flaskapp
    
 template:
  metadata:
   labels:
    app: flaskapp

  spec:
   containers:
    - name: flaskapp
      image: 172.25.4.78:5000/flaskapp:latest
      ports:
      - containerPort: 80

   imagePullSecrets:
    - name: registrypullsecret

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service

spec:
  type: LoadBalancer
  selector:
    app: flaskapp
  
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30000

